version: '3.9'

services:
  bot:
    build: ./crm_bot
    container_name: ${APPNAME}-${VERSION}
    image: ${APPNAME}:${VERSION}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
#  crm:
#    build: ./crm_django
#    container_name: crm_django
#    image: ${DJANGO_APPNAME}-${DJANGO_VERSION}
#    command: >
#      sh -c "python manage.py makemigrations &&
#             python manage.py migrate &&
#             python manage.py shell < createadmin.py &&
#             gunicorn --env DJANGO_SETTINGS_MODULE=crm_django.settings -b 0.0.0.0:8000 -w 3 crm_django.wsgi"
#    env_file:
#      - ./.env
#    ports:
#      - '8000:8000'
#    volumes:
#      - ./crm_django/logs:/app/logs
